### ISSUE TITLE
Add badges to readme

### ISSUE THREAD

**Issue by alexesprit** [nocturlab/setup-vlang-action#12]
We can add badges to the readme file to display some useful info, e.g. action version.

For my projects I prefer to add few badges (version and build status) in the readme header directly:
```md
# project-name [badge1] [badge2]
```

So, for this project badges will look like:

# setup-vlang-action ![Latest version][githubBadge] ![Workflow Status][workflowBadge]

[githubBadge]: https://img.shields.io/github/v/release/nocturlab/setup-vlang-action
[workflowBadge]: https://img.shields.io/github/workflow/status/nocturlab/setup-vlang-action/Build%20TS?label=Build%20TS

What do you think?

**Comment by shiipou** [comment]
I'vs set this badges, thanks

What about adding this one ? ![MIT license](https://img.shields.io/badge/License-MIT-blue.svg)

**Comment by alexesprit** [comment]
I would add info about license as a separate section, but not as a badge.
