### ISSUE TITLE
v1-like tags don't work until we add them

### ISSUE THREAD

**Issue by alexesprit** [nocturlab/setup-vlang-action#17]
If users will use `nocturlab/setup-vlang-action@v1` in their workflows, as it's suggested in readme, they won't be able to use the action.

Initially I thought GA finds the latest version satisfies `v1` range (e.g. `v1.0.0`, `v1.1.0`, `v1.2.0`, etc), but it does not. If we want to use `v1` shortcut, we should tag the latest release with this tag (if it satisfies this range). See [action-checkout](https://github.com/actions/checkout/releases) for example.

Alternatively, users should use either a full tag name (e.g. v1.1.0) or `master`.

**Comment by shiipou** [comment]
Oh ok, I have think it work automatically.

I'll fix it.

**Comment by shiipou** [comment]
Fixed
