### ISSUE TITLE
Managing releases

### ISSUE THREAD

**Issue by alexesprit** [nocturlab/setup-vlang-action#21]
I have a proposal regarding managing releases/tags and publishing releases.

Things to do in future:
- Bump the action version in `package.json` in a separate commit
Can be easily done via `npm version [patch|minor|major]`.
The commit message should be like "Release vX.x.x"; any similar is fine too.
This commit also should be tagged with the respective tag (e.g. `v1.1.2` for "Release v1.1.2").
- Update `v1` tag on each `v1.x.x` release (I believe it's being updated each release already)

Things we can do now:
- [x] Create (or remove) releases for existing tags
Currently we have release drafts, which should be either removed, or released.
- [x] Remove `v1.1` and `v1.0` tags
I think it's enough `v1` tag, which points to the latest `v1.x.x` tags.

What do you think?

**Comment by shiipou** [comment]
That's sound good.

I'll try to do it.

You right, the tag v1.1 is pretty useless. I did it as a formality because you can choose v1 only.
Did you think it a problem to have it ? It's getting too much in tag list ?

**Comment by alexesprit** [comment]
> Did you think it a problem to have it ? It's getting too much in tag list ?

Yes, plus, it should be also updated for patch releases. If it's useless, it makes no sense to waste time to keep pointing `v1.x` tags on the latest `v1.x.x` release.

**Comment by shiipou** [comment]
You're right.
So I'll delete it.

**Comment by shiipou** [comment]
Thanks for the suggestion.

Love this usage.
