### ISSUE TITLE
New Vlang workflow use now Weekly that make everthing deprecated here.

### ISSUE THREAD

**Issue by shiipou** [nocturlab/setup-vlang-action#72]
I need to get the list of the tags from V before downloading the code because the link is now `https://github.com/vlang/v/releases/download/weekly.2020.48.2/linux.zip` instead of `https://github.com/vlang/v/releases/download/0.1.30/v_linux.zip`

**Comment by shiipou** [comment]
Related to #66

**Comment by badouralix** [comment]
I suspect V reverted this naming change in https://github.com/vlang/v/commit/971031d8cc4dc23573287e2857e52fb2d42c4319, breaking the breaking change 😬

**Comment by shiipou** [comment]
> I suspect V reverted this naming change in [vlang/v@971031d](https://github.com/vlang/v/commit/971031d8cc4dc23573287e2857e52fb2d42c4319), breaking the breaking change 😬

Thanks @badouralix, the asset is named `v_linux.zip`. So yes, I need to revert this commit.
the problem is the latest tag was named by `V` workflow `weekly.2020.49.5`, That's pretty unpredictable name so I need to change many things to allow the action to find it. (Use the GitHub CLI to find it before trying to download it.)
But For now, I'm pretty busy with my 3 jobs. So contribution are welcome for everyone has the time. 🙏

**Comment by shiipou** [comment]
I didn't need to fix anything anymore...
Thanks `V`

<img width="1185" alt="Capture d’écran 2020-12-23 à 09 15 36" src="https://user-images.githubusercontent.com/38187238/102974884-86920d80-44ff-11eb-8e9c-838009b3e366.png">

**Comment by jacobsalmela** [comment]
Tried this on my repo and it still fails with a specific version because the artifacts are `v_linux.zip`.  Did I miss something on why it was reverted?

**Comment by shiipou** [comment]
> Tried this on my repo and it still fails with a specific version because the artifacts are `v_linux.zip`. Did I miss something on why it was reverted?

The artifact is `v_linux.zip`, 
Can you tell me the version you use ?

**Comment by shiipou** [comment]
> Tried this on my repo and it still fails with a specific version because the artifacts are `v_linux.zip`. Did I miss something on why it was reverted?

@jacobsalmela 
The artifact is `v_linux.zip`, 
Can you tell me the version you use ?

**Comment by jacobsalmela** [comment]
I tried latest, as well as `1.1.2` and `1.2.0`.  I think this issue needs to be re-opened?

**Comment by jacobsalmela** [comment]
Ah `1.2.1` does work.    Thanks.

**Comment by shiipou** [comment]
You can use `v1` of the github action to get updated.
We won't change the usage of the workflow so that will work forever (if `V` team don't change they repo settings)
If we change something that need to change the yaml file, we will create a `v2` tag
